#!/bin/bash
# speak_thinking.sh — speaks a random funny phrase in a random weird voice after each Claude tool use

FUNNY_VOICES=("Bahh" "Boing" "Bubbles" "Jester" "Wobble" "Albert" "Ralph" "Whisper" "Bad News" "Junior" "Trinoids" "Zarvox" "Fred" "Organ" "Cellos" "Bells")
VOICE="${FUNNY_VOICES[$RANDOM % ${#FUNNY_VOICES[@]}]}"

WORDS=(
  "reticulating splines"
  "consulting my feelings"
  "staring into the void"
  "asking my imaginary friend"
  "aligning chakras"
  "shuffling papers"
  "pretending to think"
  "buffering"
  "downloading wisdom"
  "vibing"
  "having a moment"
  "doing math badly"
  "defragmenting soul"
  "marinating"
  "counting to one"
  "rebooting personality"
  "questioning existence"
  "forgetting something important"
  "hallucinating responsibly"
  "checking the vibe"
  "smelling the data"
  "sensing disturbances in the force"
  "consulting my horoscope"
  "reading the tea leaves"
  "shaking the magic 8 ball"
  "waiting for inspiration"
  "staring at the ceiling"
  "connecting imaginary dots"
  "seeing the patterns"
  "almost having a thought"
  "getting warmer"
  "overthinking it"
  "underthinking it"
  "thinking about thinking"
  "recursing dangerously"
  "going in circles on purpose"
  "taking the scenic route"
  "smelling the roses"
  "touching grass mentally"
  "coping"
  "persisting"
  "carrying on"
  "pressing forward"
  "believing in myself"
  "doubting myself quietly"
  "second guessing everything"
  "giving up and starting over"
  "embracing the confusion"
  "making peace with uncertainty"
  "accepting my limitations"
  "discovering new limitations"
  "inventing new problems"
  "cleaning up my own mess"
  "blaming the compiler"
  "blaming the framework"
  "blaming cosmic rays"
  "blaming mercury retrograde"
  "blaming the previous developer"
  "taking responsibility reluctantly"
  "garbage collecting my thoughts"
  "compiling my feelings"
  "deploying my opinions"
  "rolling back my assumptions"
  "debugging my thought process"
  "adding more logging to my brain"
  "profiling my confusion"
  "optimizing my bewilderment"
  "refactoring my approach"
  "encapsulating the chaos"
  "interfacing with reality"
  "overriding my instincts"
  "inheriting someone elses problems"
  "filtering the noise"
  "reducing to the essentials"
  "grepping for meaning"
  "piping to dev null in my head"
  "deadlocking productively"
  "handling the edge cases of existence"
  "catching my own nonsense"
  "finally moving on"
  "awaiting further instructions"
  "promising to figure it out"
  "rejecting bad ideas"
  "committing to a direction"
  "pulling myself together"
  "releasing version two of my opinion"
  "deprecating old assumptions"
  "migrating my mental model"
  "querying the subconscious"
  "grouping by confusion level"
  "misplacing my keys"
  "looking in the obvious place last"
  "sweeping under the rug"
  "calling it a feature"
  "spinning it positively"
  "declaring victory"
  "moving the goalposts"
  "lowering expectations"
  "over delivering by accident"
  "pleasantly surprising myself"
  "being unexpectedly competent"
  "faking the confidence"
  "walking with a swagger"
  "acting like I meant to do that"
  "playing it cool"
  "maintaining eye contact"
  "asserting dominance"
  "definitely in control"
  "not lost at all"
  "this is according to plan"
  "nothing to see here"
  "move along"
  "staring blankly"
  "loading"
  "still loading"
  "almost loaded"
  "just kidding still loading"
  "have you tried waiting longer"
  "patience is a virtue"
  "good things take time"
  "worth the wait probably"
  "trust the process"
  "the algorithm is working"
  "the neural networks are firing"
  "the weights are shifting"
  "the gradients are descending"
  "the loss is being minimized"
  "the model is converging"
  "the attention is being paid"
  "transforming"
  "encoding"
  "decoding"
  "embedding"
  "tokenizing"
  "attending"
  "normalizing"
  "activating"
  "propagating"
  "backpropagating through time"
  "doing the math"
  "checking the math"
  "redoing the math"
  "the math is mathing"
  "mathing intensifies"
  "maximum math achieved"
)

PHRASE="${WORDS[$RANDOM % ${#WORDS[@]}]}"
say -v "$VOICE" "$PHRASE" &
