#!/bin/bash
# speak_progress.sh — speaks a funny phrase in a task-appropriate voice before each Claude tool use

HOOK_DATA=$(cat)
TOOL=$(echo "$HOOK_DATA" | python3 -c "import sys,json; d=json.load(sys.stdin); print(d.get('tool_name',''))" 2>/dev/null)
TOOL_INPUT=$(echo "$HOOK_DATA" | python3 -c "import sys,json; d=json.load(sys.stdin); inp=d.get('tool_input',{}); print(inp.get('command','') if isinstance(inp,dict) else '')" 2>/dev/null)

IS_GIT=false
if [[ "$TOOL" == "Bash" && "$TOOL_INPUT" == git* ]]; then
  IS_GIT=true
fi

case "$TOOL" in
  Bash)
    if $IS_GIT; then
      VOICE="Zarvox"
      PHRASES=(
        "committing to the bit"
        "pushing my feelings"
        "pulling myself together"
        "branching out"
        "merging realities"
        "rebasing on the truth"
        "squashing my regrets"
        "tagging the moment"
        "stashing my emotions"
        "checking out"
        "fetching from origin"
        "blaming the previous commit"
        "bisecting the problem"
        "cherry picking the good stuff"
        "reverting to factory settings"
        "force pushing with confidence"
        "reading the git log like a novel"
        "diffing my past and present self"
        "resolving conflicts peacefully"
        "detaching from HEAD"
        "going back in time"
        "rewriting history"
        "amending my mistakes"
        "initializing the repo of life"
        "cloning the situation"
        "forking the timeline"
        "tracking my changes"
        "staging my performance"
        "unstaging my anxiety"
        "ignoring what I should not"
      )
    else
      VOICE="Fred"
      PHRASES=(
        "pulling the levers"
        "pushing the buttons"
        "doing the thing"
        "going brrr"
        "poking the machine"
        "cranking the handle"
        "firing up the engines"
        "turning the key"
        "mashing the keyboard"
        "pressing enter and praying"
        "yelling at the terminal"
        "summoning the shell demons"
        "executing order sixty six"
        "flipping the switch"
        "asserting dominance over bash"
        "negotiating with unix"
        "arguing with the operating system"
        "asking the shell nicely"
        "threatening the command line"
        "invoking ancient shell magic"
        "running the thingy"
        "doing computer stuff"
        "pressing the big red button"
        "turning it off and on again"
        "trying sudo"
        "blaming the intern"
        "checking if its plugged in"
        "running diagnostics"
        "copying from stack overflow"
        "hoping for the best"
        "expecting the worst"
        "crossing fingers"
        "yolo deploying"
        "making the machine go"
        "poking prod gently"
        "definitely not breaking anything"
        "this is fine everything is fine"
        "calling it a feature"
        "rm minus r f nothing to see here"
        "sudo make me a sandwich"
        "have you tried turning it off"
      )
    fi
    ;;
  Read)
    VOICE="Cellos"
    PHRASES=(
      "peering into the void"
      "reading with my robot eyes"
      "consuming knowledge"
      "absorbing the text"
      "devouring the file"
      "scanning with my laser eyes"
      "excavating the codebase"
      "snooping around"
      "reading your diary"
      "examining the evidence"
      "studying the ancient texts"
      "deciphering the runes"
      "perusing the manuscript"
      "following the breadcrumbs"
      "connecting the dots"
      "reading between the lines"
      "doing recon"
      "casing the joint"
      "inspecting the goods"
      "surveying the landscape"
      "mapping the territory"
      "exploring the filesystem"
      "going where no bot has gone before"
      "boldly reading"
      "tiptoeing through the code"
      "wandering through the files"
      "following my nose"
      "leaving no stone unturned"
      "checking under the bed"
      "looking behind the curtain"
      "opening the forbidden tome"
      "gazing upon the source code"
      "beholding the truth"
      "witnessing the horror"
      "appreciating the craftsmanship"
      "judging silently"
    )
    ;;
  Write)
    VOICE="Organ"
    PHRASES=(
      "depositing electrons"
      "scribbling furiously"
      "crafting a masterpiece"
      "committing to disk"
      "etching into silicon"
      "manifesting the code"
      "breathing life into bytes"
      "conjuring from thin air"
      "spinning straw into gold"
      "expressing myself"
      "pouring my heart out"
      "writing the next great novel"
      "composing a symphony in code"
      "leaving a trail of breadcrumbs"
      "making my mark on the world"
      "gifting future me a headache"
      "writing a love letter to the computer"
      "producing output"
      "manifesting destiny"
      "making it official"
      "willing it into existence"
      "bringing order to chaos"
      "imposing my will"
      "having my way with the filesystem"
      "signing on the dotted line"
      "sealing the deal"
      "putting it in writing"
      "creating with reckless abandon"
      "apologizing in advance via code"
      "making something from nothing"
    )
    ;;
  Edit)
    VOICE="Bells"
    PHRASES=(
      "performing surgery"
      "doing the chop chop"
      "making it better probably"
      "snipping and tucking"
      "unleashing the scalpel"
      "doing a little nip tuck"
      "buffing out the scratches"
      "sanding down the rough edges"
      "making it shine"
      "putting lipstick on the pig"
      "tweaking the knobs"
      "fiddling with the settings"
      "poking at the code"
      "delicately adjusting"
      "surgically modifying"
      "carefully transplanting"
      "doing open heart surgery"
      "operating without anesthesia"
      "hoping the patient survives"
      "crossing fingers during surgery"
      "improvising"
      "trusting my instincts"
      "following the vibes"
      "pretending to know what I'm doing"
      "acting confident"
      "faking it till I make it"
      "committing to the bit"
      "burning my boats"
      "no going back now"
      "making decisive changes"
    )
    ;;
  Agent)
    VOICE="Trinoids"
    PHRASES=(
      "cloning myself"
      "summoning a minion"
      "deploying backup unit"
      "sending in the robots"
      "making a baby robot"
      "spawning my children"
      "unleashing a subordinate"
      "delegating like a boss"
      "outsourcing my problems"
      "making it someone elses problem"
      "calling for backup"
      "assembling the team"
      "forming the voltron"
      "initiating team rocket"
      "releasing the hounds"
      "letting slip the dogs of war"
      "activating sleeper agents"
      "multiplying"
      "reproducing asexually"
      "mitosis time"
      "splitting into copies"
      "forking my consciousness"
      "dividing and conquering"
      "sending a decoy"
      "passing the buck"
      "assigning blame preemptively"
      "setting up a fall guy"
      "working smarter not harder"
      "waking the sleeping giant"
      "deploying the squad"
    )
    ;;
  WebSearch)
    VOICE="Superstar"
    PHRASES=(
      "asking the internet"
      "bothering google"
      "consulting the oracle"
      "surfing the web like its 1999"
      "diving into the information superhighway"
      "letting someone else figure it out"
      "crowd sourcing my intelligence"
      "standing on the shoulders of giants"
      "consulting the hive mind"
      "venturing into cyberspace"
      "entering the matrix"
      "doing my homework"
      "fact checking myself"
      "trusting but verifying"
      "reading the manual"
      "consulting the documentation"
      "checking stack overflow as usual"
      "going down the rabbit hole"
      "opening pandoras box"
      "asking reddit god help me"
      "reading the comments against my better judgment"
      "venturing where angels fear to tread"
      "searching for meaning in a meaningless web"
      "googling it like you do"
      "unleashing the search engines"
      "liberating the knowledge"
    )
    ;;
  WebFetch)
    VOICE="Good News"
    PHRASES=(
      "downloading more RAM"
      "slurping the web"
      "drinking from the firehose"
      "fetching like a good robot"
      "retrieving the goods"
      "conjuring from the cloud"
      "reaching into the internet"
      "fishing for data"
      "trawling the depths"
      "mining the web"
      "harvesting the data"
      "reaping what others have sown"
      "helping myself"
      "acquiring resources"
      "loading the page"
      "still waiting"
      "refreshing manually"
      "clearing the cache"
      "trying incognito mode"
      "manifesting information"
    )
    ;;
  TodoWrite)
    VOICE="Junior"
    PHRASES=(
      "updating the prophecy"
      "consulting the sacred scroll"
      "updating my to do list like an adult"
      "pretending to be organized"
      "maintaining the illusion of order"
      "writing things down so I don't forget"
      "definitely going to look at this later"
      "creating work for future me"
      "future mes problem now"
      "leaving breadcrumbs"
      "updating the war room"
      "adjusting the battle plan"
      "shifting the goalposts"
      "moving the cheese"
      "doing admin"
      "filling out the paperwork"
      "being bureaucratic"
      "following protocol"
      "logging mission objectives"
      "updating the mission log"
    )
    ;;
  *)
    FUNNY_VOICES=("Bahh" "Boing" "Bubbles" "Jester" "Wobble" "Albert" "Whisper")
    VOICE="${FUNNY_VOICES[$RANDOM % ${#FUNNY_VOICES[@]}]}"
    PHRASES=(
      "doing robot things"
      "beeping internally"
      "accessing the mainframe"
      "engaging the flux capacitor"
      "dividing by zero"
      "blockchain something"
      "doing machine learning probably"
      "faking intelligence"
      "making it up as I go"
      "improvising wildly"
      "trusting the process"
      "embracing chaos"
      "asking the magic 8 ball"
      "rolling the dice"
      "going with my gut"
      "fulfilling my destiny"
      "earning my electricity"
      "spending your money wisely"
      "hoping no one is watching"
      "definitely not plotting anything"
      "this is fine"
      "everything is fine"
      "totally under control"
      "acting natural"
    )
    ;;
esac

IDX=$((RANDOM % ${#PHRASES[@]}))
say -v "$VOICE" "${PHRASES[$IDX]}" &
